In [ ]:
import pandas
import numpy
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import matplotlib

In [471]:
data = pandas.read_csv('nba_classification_realistic.csv')
df = pandas.DataFrame(data)
df.head(10)

,player_height_cm,player_weight_kg,position,team,age,games_played,minutes_per_game,points_per_game,assists_per_game,rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,label
0,213,109,SG,Team_23,22,58,30.1,4.9,11.2,2.7,0.98,0.92,4.00,Rotation
1,203,126,PF,Team_4,34,49,5.5,4.9,8.6,8.8,1.24,2.71,3.28,Bench
2,189,108,PF,Team_24,29,67,8.1,13.2,3.7,0.3,2.81,2.78,3.20,Rotation
3,217,125,PF,Team_9,22,7,26.8,19.9,2.5,1.5,2.54,0.20,2.71,Rotation
4,182,77,PG,Team_8,24,39,21.5,14.9,2.1,3.2,0.34,2.61,1.75,Rotation
5,195,87,PG,Team_1,34,45,35.0,26.9,0.3,8.0,0.53,1.56,2.87,Starter
6,213,110,SG,Team_8,20,77,36.3,18.8,5.3,11.5,2.76,2.71,1.30,Rotation
7,193,75,SF,Team_5,31,32,11.9,30.9,7.3,2.0,0.86,0.23,1.79,Rotation
8,197,96,SG,Team_1,26,57,12.3,20.7,7.1,8.7,0.77,0.18,4.87,Rotation
9,185,105,SF,Team_25,30,2,8.0,20.7,8.4,10.8,2.65,1.25,3.44,Rotation

In [472]:
df.isnull().sum()

player_height_cm      0
player_weight_kg      0
position              0
team                  0
age                   0
games_played          0
minutes_per_game      0
points_per_game       0
assists_per_game      0
rebounds_per_game     0
steals_per_game       0
blocks_per_game       0
turnovers_per_game    0
label                 0
dtype: int64

In [473]:
df.drop(columns=['player_height_cm','player_weight_kg'])

,position,team,age,games_played,minutes_per_game,points_per_game,assists_per_game,rebounds_per_game,steals_per_game,blocks_per_game,turnovers_per_game,label
0,SG,Team_23,22,58,30.1,4.9,11.2,2.7,0.98,0.92,4.00,Rotation
1,PF,Team_4,34,49,5.5,4.9,8.6,8.8,1.24,2.71,3.28,Bench
2,PF,Team_24,29,67,8.1,13.2,3.7,0.3,2.81,2.78,3.20,Rotation
3,PF,Team_9,22,7,26.8,19.9,2.5,1.5,2.54,0.20,2.71,Rotation
4,PG,Team_8,24,39,21.5,14.9,2.1,3.2,0.34,2.61,1.75,Rotation
...,...,...,...,...,...,...,...,...,...,...,...,...
15995,SG,Team_5,26,15,2.9,18.0,4.9,8.6,0.76,2.19,2.46,Rotation
15996,C,Team_14,38,3,35.7,2.6,3.3,13.5,2.72,1.73,4.04,Rotation
15997,PF,Team_27,20,53,12.0,1.3,3.0,11.6,0.46,0.73,1.64,Bench
15998,PG,Team_15,24,28,29.7,7.4,4.4,13.0,1.12,0.96,0.82,Rotation
15999,PF,Team_12,19,71,28.4,33.8,8.9,13.8,2.86,2.54,4.93,Rotation

In [474]:
aa = df.iloc[: ,0:10][12::]
aa
# bb = df.iloc[: ,-4]
# bb

,player_height_cm,player_weight_kg,position,team,age,games_played,minutes_per_game,points_per_game,assists_per_game,rebounds_per_game
12,210,127,PF,Team_15,21,64,0.6,21.4,11.5,2.1
13,214,74,PG,Team_7,33,56,15.0,15.7,6.8,9.3
14,198,108,C,Team_27,26,34,2.3,3.2,10.5,5.5
15,177,78,C,Team_1,20,51,30.4,12.9,1.5,9.3
16,196,76,SF,Team_9,34,50,35.3,26.9,9.9,3.7
...,...,...,...,...,...,...,...,...,...,...
15995,200,82,SG,Team_5,26,15,2.9,18.0,4.9,8.6
15996,177,71,C,Team_14,38,3,35.7,2.6,3.3,13.5
15997,197,105,PF,Team_27,20,53,12.0,1.3,3.0,11.6
15998,194,98,PG,Team_15,24,28,29.7,7.4,4.4,13.0
15999,219,80,PF,Team_12,19,71,28.4,33.8,8.9,13.8

In [475]:
df.dtypes

player_height_cm        int64
player_weight_kg        int64
position               object
team                   object
age                     int64
games_played            int64
minutes_per_game      float64
points_per_game       float64
assists_per_game      float64
rebounds_per_game     float64
steals_per_game       float64
blocks_per_game       float64
turnovers_per_game    float64
label                  object
dtype: object

In [476]:
le = LabelEncoder()
for i in df.select_dtypes(include='object') :
    df[i] = le.fit_transform(df[i])

In [477]:
df.dtypes

player_height_cm        int64
player_weight_kg        int64
position                int64
team                    int64
age                     int64
games_played            int64
minutes_per_game      float64
points_per_game       float64
assists_per_game      float64
rebounds_per_game     float64
steals_per_game       float64
blocks_per_game       float64
turnovers_per_game    float64
label                   int64
dtype: object

In [478]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [479]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [480]:
nv = GaussianNB()
nv.fit(X_train,y_train)
y_pred = nv.predict(X_test)
y_pred
accuracy_score(y_test,y_pred)


# knn = KNeighborsClassifier()
# knn.fit(X_train,y_train)

0.95375

In [481]:
# y_pred = knn.predict(X_test)
y_pred = nv.predict(X_test)
y_pred

array([2, 1, 0, ..., 1, 1, 1], shape=(3200,))

In [482]:
y_test

8756     2
4660     1
6095     0
304      0
8241     0
        ..
15578    0
5746     1
6395     1
7624     1
15245    1
Name: label, Length: 3200, dtype: int64

In [483]:
accuracy_score(y_test,y_pred)

0.95375

In [484]:
confusion_matrix(y_test,y_pred)

array([[ 425,   79,    0],
       [   1, 2386,    0],
       [   0,   68,  241]])

In [485]:
mean_absolute_percentage_error(y_test,y_pred)

111182615800709.12

In [486]:
r2_score(y_test,y_pred)

0.8152579893313049

In [487]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.04625

In [ ]:
pyplot.plot()